WebShop/Areas/Admin/Controllers/AdminPagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using WebShop.Helpper;
using WebShop.Models;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AdminPagesController : Controller
    {
        private readonly dbMarketsContext _context;
        public INotyfService _notyfService { get; }
        public AdminPagesController(dbMarketsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminPages
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsPages = _context.Pages
                .AsNoTracking()
                .OrderBy(x => x.PageId);
            PagedList<Page> models = new PagedList<Page>(lsPages, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminPages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // GET: Admin/AdminPages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PageId,PageName,Contents,Thumb,Published,Title,MetaDesc,MetaKey,Alias,CreatedDate,Ordering")] Page page, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {

                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string imageName = Utilities.SEOUrl(page.PageName) + extension;
                    page.Thumb = await Utilities.UploadFile(fThumb, @"pages", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                page.Alias = Utilities.SEOUrl(page.PageName);
                _context.Add(page);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm mới thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages.FindAsync(id);
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

        // POST: Admin/AdminPages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PageId,PageName,Contents,Thumb,Published,Title,MetaDesc,MetaKey,Alias,CreatedDate,Ordering")] Page page, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != page.PageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string imageName = Utilities.SEOUrl(page.PageName) + extension;
                        page.Thumb = await Utilities.UploadFile(fThumb, @"pages", imageName.ToLower());
                    }
                    if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                    page.Alias = Utilities.SEOUrl(page.PageName);
                    _context.Update(page);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PageExists(page.PageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // POST: Admin/AdminPages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var page = await _context.Pages.FindAsync(id);
            _context.Pages.Remove(page);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool PageExists(int id)
        {
            return _context.Pages.Any(e => e.PageId == id);
        }
    }
}

WebShop/Areas/Admin/Views/AdminPages/Create.cshtml
@model WebShop.Models.Page

@{ ViewData["Title"] = "Tạo mới Page";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }
@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <span class="breadcrumb-item active">Tạo mới Page</span>
        </nav>
    </div>
</div>

<form asp-controller="AdminPages" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Tạo mới Page</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN PAGE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên Page</label>
                        <input type="text" class="form-control" asp-for="PageName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ShortDesc">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                    </div>
                   
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="form-group d-flex align-items-center">
                            <div class="checkbox">
                                <input asp-for="Published" type="checkbox" />
                                <label for="Published">Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea class="summernote" asp-for="Contents"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

WebShop/Areas/Admin/Views/AdminPages/Delete.cshtml
@model WebShop.Models.Page

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Page</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contents)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contents)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumb)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ordering)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ordering)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PageId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebShop/Areas/Admin/Views/AdminPages/Details.cshtml
@model WebShop.Models.Page

@{ ViewData["Title"] = "Chi tiết Page :" + Model.PageName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminPages" asp-action="Index" class="breadcrumb-item">Danh sách Page</a>
            <span class="breadcrumb-item active">Thông tin Page : @Model.PageName</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:70px; width:70px">
                <img src="~/images/pages/@Model.Thumb" alt="@Model.Title" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.PageName</h4>
                <p class="text-muted m-b-0">ID: #@Model.PageId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminPages" asp-action="Edit" asp-route-id="@Model.PageId">Edit</a>
        </div>
    </div>
</div>









<h1>Details</h1>

<div>
    <h4>Page</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PageName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PageName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Contents)
        </dt>
        <dd class="col-sm-10">
            @Html.Raw(Model.Contents)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Thumb)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ordering)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ordering)
        </dd>
    </dl>
</div>

WebShop/Areas/Admin/Views/AdminPages/Edit.cshtml
@model WebShop.Models.Page

@{ ViewData["Title"] = "Chỉnh sửa Page: " + Model.PageName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }
@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <span class="breadcrumb-item active">Chỉnh sửa Page: @Model.PageName</span>
        </nav>
    </div>
</div>

<form asp-controller="AdminPages" asp-action="Edit" asp-route-id="@Model.PageId" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="PageId" />
    <input type="hidden" asp-for="Thumb" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu thay đổi</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN PAGE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên Page</label>
                        <input type="text" class="form-control" asp-for="PageName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ShortDesc">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="form-group d-flex align-items-center">
                            <div class="checkbox">
                                <input asp-for="Published" type="checkbox" />
                                <label for="Published">Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea class="summernote" asp-for="Contents"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

WebShop/Areas/Admin/Views/AdminPages/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<WebShop.Models.Page>
@{ int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách Page" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }


<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <span class="breadcrumb-item active">Danh sách Page : trang @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminPages" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm Page</span></a>
            </div>
            <div class="col-lg-4 text-right">
                
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên Page</th>
                        <th>Trạng thái</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            string url = $"/page/{item.Alias}";
        <tr>
            <td>@item.PageId</td>
            <td><a target="_blank" href="@url">@item.PageName</a></td>
            <td>
                @if (item.Published == true)
                {


    <div class="d-flex align-items-center">
        <div class="badge badge-success badge-dot m-r-10"></div>
        <div>Public</div>
    </div> }
else
{
    <div class="d-flex align-items-center">
        <div class="badge badge-success badge-dot m-r-10"></div>
        <div>Non-Public</div>
    </div>}


            </td>

            <td>
                <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPages" asp-action="Details" asp-route-id="@item.PageId">Chi tiết</a>
                <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPages" asp-action="Edit" asp-route-id="@item.PageId">Sửa</a>
                <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPages" asp-action="Delete" asp-route-id="@item.PageId">Xóa</a>
            </td>
        </tr>}
                    }

                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminPages" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>